### ISSUE TITLE
Armor physics doesn't work

### ISSUE THREAD

**Issue by Snans101** [WildfireRomeo/WildfireFemaleGenderMod#101]
So, I used the mod but when I turned on armor physics it stopped working
![image](https://user-images.githubusercontent.com/88905878/222567771-f72c6c4c-c5ac-4f37-942d-a7036fa038eb.png)

https://user-images.githubusercontent.com/88905878/222568282-e4ff0db4-1d18-4601-97d5-6e2316bc1c69.mp4

I am on fabric 1.19.2

**Comment by Interstellar73** [comment]
armor physics were removed.

As staded on the modrinth page: "I removed the armor physics toggle button as it no longer did anything to affect breast physics when armor was worn. It was misleading to many and I planned on removing it anyway. Breast physics will from now on be affected by the material/type of armor being worn instead of just having it on or off."

**Comment by Snans101** [comment]
Oh ok
