### ISSUE TITLE
1.12 please

### ISSUE THREAD

**Issue by Aceplante2** [WildfireRomeo/WildfireFemaleGenderMod#121]
I hope this isn't too difficult, but a lot of people still play 1.12 specifically, and support for that version (though I know is not planned), would be much appreciated.

**Comment by JunoBat** [comment]
I don't think the mod will be ported to 1.12 because of how marginally different that version is in its code, so I suggest you could use [More Player Models](https://www.curseforge.com/minecraft/mc-mods/more-player-models) which already has an option for breasts (tho, no scaling for them, you just pick between 2 or 3 presets). I guess your satisfaction depends on how customizable you'd want the mod to be.

**Comment by Aceplante2** [comment]
1.12 seems to be a version that a lot of people stay on, and has a lot of amazing mods for it that were never updated. I was just trying it out but I think it would be greatly appreciated by many if you did

**Comment by WildfireRomeo** [comment]
1.12 is not happening officially. If someone ports it themselves to older versions I'm happy to share it, but I won't be doing it myself.
