### ISSUE TITLE
Gender reset from rejoin

### ISSUE THREAD

**Issue by PengWanYT** [WildfireRomeo/WildfireFemaleGenderMod#260]
Well I was testing the mod new latest version

When I was use female gender, then rejoin again, it turn back male gender 😭

**Comment by PengWanYT** [comment]
Uploading XRecorder_10122024_223620.mp4…

**Comment by PengWanYT** [comment]
https://youtu.be/qgxiKMMmgNM?si=oAjMtfnDrsMMXfNd

Video link here, it's was on server gender mod, even single-player will reset gender too of rejoin

**Comment by TransBluelight** [comment]
> Probaly is a broken perms to path issue (because you're on mobile) Mabye try enabling could sync?

it definitely could be a permission issue, renaming the PojavLauncher folder on Android 12+ to a different package name (since PojavLauncher has two flavors, stable play store release and GitHub debug builds, which both have different package names) they could of simply renamed net.kdt.pojavlauncher to net.kdt.pojavlauncher.debug and that breaks the permission the app has on writing to that folder, since it wasn't originally created by the app, they should try making a world and seeing if it even saves, if it saves then it's probably a whole different issue

**Comment by TransBluelight** [comment]
so if old versions work then the issue is probably related to something to do with cloud synching, show us the log you get on the cloud synching part (click on the little cloud icon besides the gender button)

**Comment by PengWanYT** [comment]
https://youtu.be/wZHKGYUtJp4?si=5bG4WyfwAK4XFh92

Well when I am go sync menu look like,

But when I am clock sync it, it say sync failed ._.

**Comment by TransBluelight** [comment]
it seems like you don't own Minecraft as the mod gets stuck on authenticating, the mod has to authenticate with a legitimate account on Mojang's servers, wildfire did this to avoid DDoS attacks on her synch server
Also, you can't say Pojav breaks the authentication because I also use PojavLauncher and it works perfectly fine for me so this just you not owning Minecraft. Sorry, can't help you any further

**Comment by PengWanYT** [comment]
Ohhh okk well thx for telling, guess had waited long year to buy original minecraft ;00 👍
